GET http://localhost:8085/stocks 

### Add Stock
POST http://localhost:8085/addstock
Content-Type: application/json

{
  "name": "Example Stock",
    "price": 100.5,
    "symbol": "EXMPL"
}

### Delete Stock by symbol
DELETE http://localhost:8085/deletestock?symbol=TST