apiVersion: v1
kind: Deployment 
metadata:
  name: postgres 
  namespace: stock-analysis
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminateGracePeriodSeconds: 30
      containers:
        - name: postgres
          image: postgres:13.2
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 5432
          env: 
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: 1234
          volumeMounts: 
          - name: postgresdb
            mountPath: /var/lib/postgres
      volumes:
        - name: postgresdb 
          PersistentVolumeClaim: 
            claimName: postgres-pv
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: postgres 
  namespace: stock-analysis
spec: 
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort 
