apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  namespace: stock-analysis 
  name: pvc-postgres 
spec: 
  accessModes: 
  - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi
  storageClassName: linode-block-storage
   
