name: Stock Analysis Image

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                go-version: 1.17

            - name: Install dependencies
              run: go mod download

            - name: Run tests
              run: go test ./...

            - name: Build & push Docker image
              uses: mr-smithers-excellent/docker-build-push@v6
              with: 
                image: simonnilsson584/stock-analysis
                tags: latest 
                registry: docker.io
                dockerfile: Dockerfile
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}